"""execution_testing"""

from alembic import op
import sqlalchemy as sa

revision = "0002_execution_testing"
down_revision = "0001_reviews"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_runs",
        sa.Column("execution_run_id", sa.String(length=36), nullable=False),
        sa.Column("workflow_run_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("execution_profile", sa.String(length=32), nullable=False),
        sa.Column("engine", sa.String(length=32), nullable=False),
        sa.Column("sql_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("failure_category", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approval_records.approval_id"],
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.PrimaryKeyConstraint("execution_run_id"),
    )
    op.create_table(
        "metric_test_runs",
        sa.Column("test_run_id", sa.String(length=36), nullable=False),
        sa.Column("execution_run_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("skipped", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["execution_run_id"],
            ["execution_runs.execution_run_id"],
        ),
        sa.PrimaryKeyConstraint("test_run_id"),
    )
    op.create_table(
        "metric_test_results",
        sa.Column("test_case_id", sa.String(length=36), nullable=False),
        sa.Column("test_run_id", sa.String(length=36), nullable=False),
        sa.Column("test_type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("failure_category", sa.String(length=32), nullable=True),
        sa.Column("expected_summary", sa.String(length=1000), nullable=False),
        sa.Column("actual_summary", sa.String(length=1000), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["test_run_id"],
            ["metric_test_runs.test_run_id"],
        ),
        sa.PrimaryKeyConstraint("test_case_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_test_results")
    op.drop_table("metric_test_runs")
    op.drop_table("execution_runs")
    # ### end Alembic commands ###
