"""environment_validation"""

from alembic import op
import sqlalchemy as sa

revision = "0003_environment_validation"
down_revision = "0002_execution_testing"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environment_validation_runs",
        sa.Column("validation_run_id", sa.String(length=36), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=False),
        sa.Column("profile_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("engine_version", sa.String(length=256), nullable=True),
        sa.Column("session_timezone", sa.String(length=128), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("validation_run_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("environment_validation_runs")
    # ### end Alembic commands ###
