"""controlled_refinement"""

from alembic import op
import sqlalchemy as sa

revision = "0006_controlled_refinement"
down_revision = "0005_experiment_reflection"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposal_decisions",
        sa.Column("decision_id", sa.String(length=36), nullable=False),
        sa.Column("reflection_run_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("proposal_hash", sa.String(length=64), nullable=False),
        sa.Column("decision_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reflection_run_id"],
            ["reflection_runs.reflection_run_id"],
        ),
        sa.PrimaryKeyConstraint("decision_id"),
        sa.UniqueConstraint("reflection_run_id", "proposal_id"),
    )
    op.create_table(
        "refinement_runs",
        sa.Column("refinement_run_id", sa.String(length=36), nullable=False),
        sa.Column("reflection_run_id", sa.String(length=36), nullable=False),
        sa.Column("decision_id", sa.String(length=36), nullable=False),
        sa.Column("proposal_id", sa.String(length=64), nullable=False),
        sa.Column("baseline_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_experiment_run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("final_decision_recorded", sa.Boolean(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("candidate_test_run_id", sa.String(length=36), nullable=True),
        sa.Column("candidate_experiment_run_id", sa.String(length=36), nullable=True),
        sa.Column("comparison_policy_version", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["baseline_artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["baseline_experiment_run_id"],
            ["experiment_runs.experiment_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["proposal_decisions.decision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["reflection_run_id"],
            ["reflection_runs.reflection_run_id"],
        ),
        sa.PrimaryKeyConstraint("refinement_run_id"),
    )
    op.create_table(
        "refinement_reports",
        sa.Column("refinement_run_id", sa.String(length=36), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("coverage_delta", sa.Float(), nullable=True),
        sa.Column("ks_delta", sa.Float(), nullable=True),
        sa.Column("iv_delta", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["refinement_run_id"],
            ["refinement_runs.refinement_run_id"],
        ),
        sa.PrimaryKeyConstraint("refinement_run_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("refinement_reports")
    op.drop_table("refinement_runs")
    op.drop_table("proposal_decisions")
    # ### end Alembic commands ###
