"""temporal_validation_promotion"""

from alembic import op
import sqlalchemy as sa

# Alembic's default version_num is VARCHAR(32), including on MySQL.
revision = "0007_temporal_validation"
down_revision = "0006_controlled_refinement"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temporal_dataset_series",
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=2000), nullable=False),
        sa.Column("reference_slice_id", sa.String(length=36), nullable=False),
        sa.Column("oot_slice_id", sa.String(length=36), nullable=False),
        sa.Column("series_json", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("series_id"),
    )
    op.create_table(
        "temporal_validation_runs",
        sa.Column("temporal_validation_run_id", sa.String(length=36), nullable=False),
        sa.Column("source_refinement_run_id", sa.String(length=36), nullable=False),
        sa.Column("baseline_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("series_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stability_policy_version", sa.String(length=32), nullable=False),
        sa.Column("promotion_policy_version", sa.String(length=32), nullable=False),
        sa.Column("spec_hash", sa.String(length=64), nullable=False),
        sa.Column("spec_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["baseline_artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["temporal_dataset_series.series_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_refinement_run_id"],
            ["refinement_runs.refinement_run_id"],
        ),
        sa.PrimaryKeyConstraint("temporal_validation_run_id"),
        sa.UniqueConstraint("source_refinement_run_id"),
    )
    op.create_table(
        "promotion_reviews",
        sa.Column("promotion_review_id", sa.String(length=36), nullable=False),
        sa.Column("temporal_validation_run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_artifact_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reviewer", sa.String(length=2000), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("review_json", sa.JSON(), nullable=False),
        sa.Column("review_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["temporal_validation_run_id"],
            ["temporal_validation_runs.temporal_validation_run_id"],
        ),
        sa.PrimaryKeyConstraint("promotion_review_id"),
        sa.UniqueConstraint("temporal_validation_run_id"),
    )
    op.create_table(
        "temporal_validation_results",
        sa.Column("temporal_validation_run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("promotion_eligibility", sa.String(length=32), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.Column("report_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["temporal_validation_run_id"],
            ["temporal_validation_runs.temporal_validation_run_id"],
        ),
        sa.PrimaryKeyConstraint("temporal_validation_run_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temporal_validation_results")
    op.drop_table("promotion_reviews")
    op.drop_table("temporal_validation_runs")
    op.drop_table("temporal_dataset_series")
    # ### end Alembic commands ###
