"""metric_registry_release"""

from alembic import op
import sqlalchemy as sa

# Alembic's default version_num is VARCHAR(32), including on MySQL.
revision = "0008_metric_registry_release"
down_revision = "0007_temporal_validation"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_definitions",
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("metric_key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=2000), nullable=False),
        sa.Column("scenario", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("member_metric_names", sa.JSON(), nullable=False),
        sa.Column("active_version_id", sa.String(length=36), nullable=True),
        sa.Column("definition_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("metric_definition_id"),
        sa.UniqueConstraint("metric_key"),
    )
    op.create_table(
        "metric_versions",
        sa.Column("metric_version_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=64), nullable=False),
        sa.Column("metric_ir_hash", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("source_promotion_review_id", sa.String(length=36), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("version_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["development_artifacts.artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.metric_definition_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_promotion_review_id"],
            ["promotion_reviews.promotion_review_id"],
        ),
        sa.PrimaryKeyConstraint("metric_version_id"),
        sa.UniqueConstraint("metric_definition_id", "version"),
        sa.UniqueConstraint("source_promotion_review_id"),
    )
    op.create_table(
        "metric_releases",
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("target_environment", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expected_active_version_id", sa.String(length=36), nullable=True),
        sa.Column("release_policy_version", sa.String(length=32), nullable=False),
        sa.Column("release_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("validated_at", sa.DateTime(), nullable=True),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.metric_definition_id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_version_id"],
            ["metric_versions.metric_version_id"],
        ),
        sa.PrimaryKeyConstraint("release_id"),
    )
    op.create_table(
        "rollback_reviews",
        sa.Column("rollback_review_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("from_version_id", sa.String(length=36), nullable=True),
        sa.Column("to_version_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reviewer", sa.String(length=2000), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("review_json", sa.JSON(), nullable=False),
        sa.Column("review_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.metric_definition_id"],
        ),
        sa.PrimaryKeyConstraint("rollback_review_id"),
    )
    op.create_table(
        "release_reviews",
        sa.Column("release_review_id", sa.String(length=36), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reviewer", sa.String(length=2000), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("review_json", sa.JSON(), nullable=False),
        sa.Column("review_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["metric_version_id"],
            ["metric_versions.metric_version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["metric_releases.release_id"],
        ),
        sa.PrimaryKeyConstraint("release_review_id"),
        sa.UniqueConstraint("release_id"),
    )
    op.create_table(
        "release_validation_results",
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("release_eligibility", sa.String(length=32), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.Column("report_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["metric_releases.release_id"],
        ),
        sa.PrimaryKeyConstraint("release_id"),
    )
    op.create_table(
        "metric_release_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=True),
        sa.Column("release_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("actor", sa.String(length=2000), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("metric_release_events")
    op.drop_table("release_validation_results")
    op.drop_table("release_reviews")
    op.drop_table("rollback_reviews")
    op.drop_table("metric_releases")
    op.drop_table("metric_versions")
    op.drop_table("metric_definitions")
    # ### end Alembic commands ###
