"""production_monitoring_feedback"""

from alembic import op
import sqlalchemy as sa

# Alembic's default version_num is VARCHAR(32), including on MySQL.
revision = "0009_production_monitoring_feedback"
down_revision = "0008_metric_registry_release"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "metric_feedback_events",
        sa.Column("feedback_event_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=True),
        sa.Column("deployment_id", sa.String(length=36), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("recorded_by", sa.String(length=128), nullable=False),
        sa.Column("event_json", sa.JSON(), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("feedback_event_id"),
    )
    op.create_table(
        "production_deployment_plans",
        sa.Column("deployment_plan_id", sa.String(length=36), nullable=False),
        sa.Column("package_id", sa.String(length=36), nullable=False),
        sa.Column("target_environment", sa.String(length=64), nullable=False),
        sa.Column("deployment_strategy", sa.String(length=32), nullable=False),
        sa.Column("plan_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("deployment_plan_id"),
    )
    op.create_table(
        "production_environment_profiles",
        sa.Column("environment_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=2000), nullable=False),
        sa.Column("environment_kind", sa.String(length=32), nullable=False),
        sa.Column("execution_mode", sa.String(length=32), nullable=False),
        sa.Column("deployment_enabled", sa.Boolean(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("synthetic_profile", sa.Boolean(), nullable=False),
        sa.Column("environment_validation_run_id", sa.String(length=36), nullable=True),
        sa.Column("profile_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("environment_id"),
    )
    op.create_table(
        "feedback_research_requests",
        sa.Column("research_request_id", sa.String(length=36), nullable=False),
        sa.Column("feedback_event_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=True),
        sa.Column("request_type", sa.String(length=32), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("request_json", sa.JSON(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feedback_event_id"],
            ["metric_feedback_events.feedback_event_id"],
        ),
        sa.PrimaryKeyConstraint("research_request_id"),
    )
    op.create_table(
        "production_deployments",
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=False),
        sa.Column("release_id", sa.String(length=36), nullable=False),
        sa.Column("environment_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("deployment_package_hash", sa.String(length=64), nullable=False),
        sa.Column("provider_job_id", sa.String(length=128), nullable=True),
        sa.Column("runtime_mode", sa.String(length=32), nullable=False),
        sa.Column("production_deployed", sa.Boolean(), nullable=False),
        sa.Column("runtime_binding_json", sa.JSON(), nullable=True),
        sa.Column("deployment_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deployed_at", sa.DateTime(), nullable=True),
        sa.Column("rolled_back_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["metric_definitions.metric_definition_id"],
        ),
        sa.ForeignKeyConstraint(
            ["metric_version_id"],
            ["metric_versions.metric_version_id"],
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["metric_releases.release_id"],
        ),
        sa.PrimaryKeyConstraint("deployment_id"),
    )
    op.create_table(
        "metric_alerts",
        sa.Column("alert_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("recommended_action", sa.String(length=32), nullable=False),
        sa.Column("alert_json", sa.JSON(), nullable=False),
        sa.Column("alert_hash", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["production_deployments.deployment_id"],
        ),
        sa.PrimaryKeyConstraint("alert_id"),
        sa.UniqueConstraint("dedup_key"),
    )
    op.create_table(
        "metric_monitoring_snapshots",
        sa.Column("monitoring_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=False),
        sa.Column("observation_time", sa.DateTime(), nullable=False),
        sa.Column("execution_status", sa.String(length=32), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("psi", sa.Float(), nullable=True),
        sa.Column("source_system", sa.String(length=2000), nullable=False),
        sa.Column("source_event_id", sa.String(length=2000), nullable=False),
        sa.Column("publisher_actor_id", sa.String(length=128), nullable=False),
        sa.Column("snapshot_json", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["production_deployments.deployment_id"],
        ),
        sa.PrimaryKeyConstraint("monitoring_snapshot_id"),
    )
    op.create_table(
        "production_deployment_reviews",
        sa.Column("deployment_review_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("metric_version_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("reviewer", sa.String(length=2000), nullable=True),
        sa.Column("reviewer_actor_id", sa.String(length=128), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("package_hash", sa.String(length=64), nullable=False),
        sa.Column("review_json", sa.JSON(), nullable=False),
        sa.Column("review_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["production_deployments.deployment_id"],
        ),
        sa.PrimaryKeyConstraint("deployment_review_id"),
        sa.UniqueConstraint("deployment_id"),
    )
    op.create_table(
        "production_rollback_reviews",
        sa.Column("rollback_review_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=36), nullable=False),
        sa.Column("metric_definition_id", sa.String(length=36), nullable=False),
        sa.Column("from_version_id", sa.String(length=36), nullable=False),
        sa.Column("to_version_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("production_rollback_status", sa.String(length=32), nullable=False),
        sa.Column("registry_reconciliation_status", sa.String(length=32), nullable=False),
        sa.Column("provider_job_id", sa.String(length=128), nullable=True),
        sa.Column("reviewer", sa.String(length=2000), nullable=True),
        sa.Column("reviewer_actor_id", sa.String(length=128), nullable=True),
        sa.Column("review_json", sa.JSON(), nullable=False),
        sa.Column("review_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["production_deployments.deployment_id"],
        ),
        sa.PrimaryKeyConstraint("rollback_review_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("production_rollback_reviews")
    op.drop_table("production_deployment_reviews")
    op.drop_table("metric_monitoring_snapshots")
    op.drop_table("metric_alerts")
    op.drop_table("production_deployments")
    op.drop_table("feedback_research_requests")
    op.drop_table("production_environment_profiles")
    op.drop_table("production_deployment_plans")
    op.drop_table("metric_feedback_events")
    # ### end Alembic commands ###
